[build]
  publish = "."

[[redirects]]
  from = "https://www.baegwandaejang.co.kr/*"
  to = "https://baegwandaejang.co.kr/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "/:splat/"
  status = 301
  force = false

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
